// This file is auto-generated by the Python adapter pipeline.
// Do not edit manually.

/* AUTO-GENERATED REVIEW STUB
 * adapter_id: MeasurementReport__criticalExtensions__measurementReport__measResults__measId__integer_transform
 * domain_id: MeasurementReport__criticalExtensions__measurementReport__measResults__measId
 * message: MeasurementReport
 * field: measId
 * operator_family: integer_transform
 * candidate_chain: criticalExtensions.choice.measurementReport->measResults.measId
 * compile_validation: compile_verified
 * helper_function: nr_ue_fuzz_hook_apply_measid_integer_transform
 * adapter_function: nr_ue_fuzz_hook_apply_measid_integer_transform_adapter
 * payload_type: NR_MeasurementReport_t
 * review points:
 *   - confirm_oai_struct_member_path
 *   - confirm_optional_branch_and_release_extension
 *   - derived_generic_message_field_profile
 */
static bool nr_ue_fuzz_hook_apply_measid_integer_transform(NR_UE_RRC_INST_t *rrc,
                              NR_MeasurementReport_t *payload,
                              const char *mode)
{
  if (!payload)
    return false;

  if (!mode || !*mode)
    mode = "mismatch_in_range";

  long min_value = 1;
  long max_value = 64;
  long chosen_value = 2;

  if (!strcasecmp(mode, "boundary_min")) {
    chosen_value = min_value;
  } else if (!strcasecmp(mode, "boundary_max")) {
    chosen_value = max_value;
  } else if (!strcasecmp(mode, "mismatch_in_range")) {
    chosen_value = (min_value < max_value) ? (min_value + 1) : max_value;
  }

    payload->criticalExtensions.present = NR_MeasurementReport__criticalExtensions_PR_measurementReport;
    if (!payload->criticalExtensions.choice.measurementReport)
      payload->criticalExtensions.choice.measurementReport = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport));
  payload->criticalExtensions.choice.measurementReport->measResults.measId = chosen_value;
  LOG_W(NR_RRC, "[UE %ld][HOOK] mutate measId in MeasurementReport\\n", rrc->ue_id);
  return true;
}

static bool nr_ue_fuzz_hook_apply_measid_integer_transform_adapter(NR_UE_RRC_INST_t *rrc, void *payload, const char *mode)
{
  return nr_ue_fuzz_hook_apply_measid_integer_transform(rrc, (NR_MeasurementReport_t *)payload, mode);
}

/* registry entry
{
    .target_msg = NR_UE_HOOK_MSG_MEASUREMENT_REPORT,
    .message_name = "MeasurementReport",
    .field_name = "measId",
    .operator_name = "integer_transform",
    .apply = nr_ue_fuzz_hook_apply_measid_integer_transform_adapter,
},
*/

/* AUTO-GENERATED REVIEW STUB
 * adapter_id: MeasurementReport__criticalExtensions__measurementReport__measResults__measResultSFTD-EUTRA__sfn-OffsetResult__integer_transform
 * domain_id: MeasurementReport__criticalExtensions__measurementReport__measResults__measResultSFTD-EUTRA__sfn-OffsetResult
 * message: MeasurementReport
 * field: sfn-OffsetResult
 * operator_family: integer_transform
 * candidate_chain: criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->sfn_OffsetResult
 * compile_validation: compile_verified
 * helper_function: nr_ue_fuzz_hook_apply_sfn_offsetresult_integer_transform
 * adapter_function: nr_ue_fuzz_hook_apply_sfn_offsetresult_integer_transform_adapter
 * payload_type: NR_MeasurementReport_t
 * review points:
 *   - confirm_oai_struct_member_path
 *   - confirm_optional_branch_and_release_extension
 *   - derived_generic_message_field_profile
 */
static bool nr_ue_fuzz_hook_apply_sfn_offsetresult_integer_transform(NR_UE_RRC_INST_t *rrc,
                              NR_MeasurementReport_t *payload,
                              const char *mode)
{
  if (!payload)
    return false;

  if (!mode || !*mode)
    mode = "mismatch_in_range";

  long min_value = 0;
  long max_value = 1023;
  long chosen_value = 1;

  if (!strcasecmp(mode, "boundary_min")) {
    chosen_value = min_value;
  } else if (!strcasecmp(mode, "boundary_max")) {
    chosen_value = max_value;
  } else if (!strcasecmp(mode, "mismatch_in_range")) {
    chosen_value = (min_value < max_value) ? (min_value + 1) : max_value;
  }

    payload->criticalExtensions.present = NR_MeasurementReport__criticalExtensions_PR_measurementReport;
    if (!payload->criticalExtensions.choice.measurementReport)
      payload->criticalExtensions.choice.measurementReport = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport));
    if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1)
      payload->criticalExtensions.choice.measurementReport->measResults.ext1 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport->measResults.ext1));
    if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA)
      payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA));
  payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->sfn_OffsetResult = chosen_value;
  LOG_W(NR_RRC, "[UE %ld][HOOK] mutate sfn-OffsetResult in MeasurementReport\\n", rrc->ue_id);
  return true;
}

static bool nr_ue_fuzz_hook_apply_sfn_offsetresult_integer_transform_adapter(NR_UE_RRC_INST_t *rrc, void *payload, const char *mode)
{
  return nr_ue_fuzz_hook_apply_sfn_offsetresult_integer_transform(rrc, (NR_MeasurementReport_t *)payload, mode);
}

/* registry entry
{
    .target_msg = NR_UE_HOOK_MSG_MEASUREMENT_REPORT,
    .message_name = "MeasurementReport",
    .field_name = "sfn-OffsetResult",
    .operator_name = "integer_transform",
    .apply = nr_ue_fuzz_hook_apply_sfn_offsetresult_integer_transform_adapter,
},
*/

/* AUTO-GENERATED REVIEW STUB
 * adapter_id: MeasurementReport__criticalExtensions__measurementReport__measResults__measResultSFTD-EUTRA__frameBoundaryOffsetResult__integer_transform
 * domain_id: MeasurementReport__criticalExtensions__measurementReport__measResults__measResultSFTD-EUTRA__frameBoundaryOffsetResult
 * message: MeasurementReport
 * field: frameBoundaryOffsetResult
 * operator_family: integer_transform
 * candidate_chain: criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->frameBoundaryOffsetResult
 * compile_validation: compile_verified
 * helper_function: nr_ue_fuzz_hook_apply_frameboundaryoffsetresult_integer_transform
 * adapter_function: nr_ue_fuzz_hook_apply_frameboundaryoffsetresult_integer_transform_adapter
 * payload_type: NR_MeasurementReport_t
 * review points:
 *   - confirm_oai_struct_member_path
 *   - confirm_optional_branch_and_release_extension
 *   - derived_generic_message_field_profile
 */
static bool nr_ue_fuzz_hook_apply_frameboundaryoffsetresult_integer_transform(NR_UE_RRC_INST_t *rrc,
                              NR_MeasurementReport_t *payload,
                              const char *mode)
{
  if (!payload)
    return false;

  if (!mode || !*mode)
    mode = "mismatch_in_range";

  long min_value = -30720;
  long max_value = 30719;
  long chosen_value = -30719;

  if (!strcasecmp(mode, "boundary_min")) {
    chosen_value = min_value;
  } else if (!strcasecmp(mode, "boundary_max")) {
    chosen_value = max_value;
  } else if (!strcasecmp(mode, "mismatch_in_range")) {
    chosen_value = (min_value < max_value) ? (min_value + 1) : max_value;
  }

    payload->criticalExtensions.present = NR_MeasurementReport__criticalExtensions_PR_measurementReport;
    if (!payload->criticalExtensions.choice.measurementReport)
      payload->criticalExtensions.choice.measurementReport = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport));
    if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1)
      payload->criticalExtensions.choice.measurementReport->measResults.ext1 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport->measResults.ext1));
    if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA)
      payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA));
  payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->frameBoundaryOffsetResult = chosen_value;
  LOG_W(NR_RRC, "[UE %ld][HOOK] mutate frameBoundaryOffsetResult in MeasurementReport\\n", rrc->ue_id);
  return true;
}

static bool nr_ue_fuzz_hook_apply_frameboundaryoffsetresult_integer_transform_adapter(NR_UE_RRC_INST_t *rrc, void *payload, const char *mode)
{
  return nr_ue_fuzz_hook_apply_frameboundaryoffsetresult_integer_transform(rrc, (NR_MeasurementReport_t *)payload, mode);
}

/* registry entry
{
    .target_msg = NR_UE_HOOK_MSG_MEASUREMENT_REPORT,
    .message_name = "MeasurementReport",
    .field_name = "frameBoundaryOffsetResult",
    .operator_name = "integer_transform",
    .apply = nr_ue_fuzz_hook_apply_frameboundaryoffsetresult_integer_transform_adapter,
},
*/

/* AUTO-GENERATED REVIEW STUB
 * adapter_id: MeasurementReport__criticalExtensions__measurementReport__measResults__measResultSFTD-EUTRA__rsrp-Result__integer_transform
 * domain_id: MeasurementReport__criticalExtensions__measurementReport__measResults__measResultSFTD-EUTRA__rsrp-Result
 * message: MeasurementReport
 * field: rsrp-Result
 * operator_family: integer_transform
 * candidate_chain: criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result
 * compile_validation: compile_verified
 * helper_function: nr_ue_fuzz_hook_apply_rsrp_result_integer_transform
 * adapter_function: nr_ue_fuzz_hook_apply_rsrp_result_integer_transform_adapter
 * payload_type: NR_MeasurementReport_t
 * review points:
 *   - confirm_oai_struct_member_path
 *   - confirm_optional_branch_and_release_extension
 *   - derived_generic_message_field_profile
 */
static bool nr_ue_fuzz_hook_apply_rsrp_result_integer_transform(NR_UE_RRC_INST_t *rrc,
                              NR_MeasurementReport_t *payload,
                              const char *mode)
{
  if (!payload)
    return false;

  if (!mode || !*mode)
    mode = "mismatch_in_range";

  long min_value = 0;
  long max_value = 127;
  long chosen_value = 1;

  if (!strcasecmp(mode, "boundary_min")) {
    chosen_value = min_value;
  } else if (!strcasecmp(mode, "boundary_max")) {
    chosen_value = max_value;
  } else if (!strcasecmp(mode, "mismatch_in_range")) {
    chosen_value = (min_value < max_value) ? (min_value + 1) : max_value;
  }

    payload->criticalExtensions.present = NR_MeasurementReport__criticalExtensions_PR_measurementReport;
    if (!payload->criticalExtensions.choice.measurementReport)
      payload->criticalExtensions.choice.measurementReport = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport));
    if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1)
      payload->criticalExtensions.choice.measurementReport->measResults.ext1 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport->measResults.ext1));
    if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA)
      payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA));
    if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result)
      payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result = CALLOC(1, sizeof(*payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result));
  if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result)
    payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result = calloc(1, sizeof(*payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result));
  if (!payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result)
    return false;
  *payload->criticalExtensions.choice.measurementReport->measResults.ext1->measResultSFTD_EUTRA->rsrp_Result = chosen_value;
  LOG_W(NR_RRC, "[UE %ld][HOOK] mutate rsrp-Result in MeasurementReport\\n", rrc->ue_id);
  return true;
}

static bool nr_ue_fuzz_hook_apply_rsrp_result_integer_transform_adapter(NR_UE_RRC_INST_t *rrc, void *payload, const char *mode)
{
  return nr_ue_fuzz_hook_apply_rsrp_result_integer_transform(rrc, (NR_MeasurementReport_t *)payload, mode);
}

/* registry entry
{
    .target_msg = NR_UE_HOOK_MSG_MEASUREMENT_REPORT,
    .message_name = "MeasurementReport",
    .field_name = "rsrp-Result",
    .operator_name = "integer_transform",
    .apply = nr_ue_fuzz_hook_apply_rsrp_result_integer_transform_adapter,
},
*/

static const nr_ue_fuzz_hook_field_adapter_t auto_generated_field_adapters[] = {
    {
        .target_msg = NR_UE_HOOK_MSG_MEASUREMENT_REPORT,
        .message_name = "MeasurementReport",
        .field_name = "measId",
        .operator_name = "integer_transform",
        .apply = nr_ue_fuzz_hook_apply_measid_integer_transform_adapter,
    },
    {
        .target_msg = NR_UE_HOOK_MSG_MEASUREMENT_REPORT,
        .message_name = "MeasurementReport",
        .field_name = "sfn-OffsetResult",
        .operator_name = "integer_transform",
        .apply = nr_ue_fuzz_hook_apply_sfn_offsetresult_integer_transform_adapter,
    },
    {
        .target_msg = NR_UE_HOOK_MSG_MEASUREMENT_REPORT,
        .message_name = "MeasurementReport",
        .field_name = "frameBoundaryOffsetResult",
        .operator_name = "integer_transform",
        .apply = nr_ue_fuzz_hook_apply_frameboundaryoffsetresult_integer_transform_adapter,
    },
    {
        .target_msg = NR_UE_HOOK_MSG_MEASUREMENT_REPORT,
        .message_name = "MeasurementReport",
        .field_name = "rsrp-Result",
        .operator_name = "integer_transform",
        .apply = nr_ue_fuzz_hook_apply_rsrp_result_integer_transform_adapter,
    },
};

static const nr_ue_fuzz_hook_field_adapter_t *nr_ue_fuzz_hook_find_auto_field_adapter(const nr_ue_fuzz_hook_state_t *hook)
{
  if (!hook || !hook->field_mutation.enabled)
    return NULL;

  size_t count = sizeof(auto_generated_field_adapters) / sizeof(auto_generated_field_adapters[0]);
  for (size_t i = 0; i < count; ++i) {
    const nr_ue_fuzz_hook_field_adapter_t *adapter = &auto_generated_field_adapters[i];
    if (adapter->target_msg != hook->target_msg) continue;
    if (!nr_ue_fuzz_hook_text_eq(hook->field_mutation.message, adapter->message_name)) continue;
    if (!nr_ue_fuzz_hook_text_eq(hook->field_mutation.field, adapter->field_name)) continue;
    if (!nr_ue_fuzz_hook_text_eq(hook->field_mutation.operator_name, adapter->operator_name)) continue;
    return adapter;
  }
  
  return NULL;
}
