// This file is auto-generated by the Python adapter pipeline.
// Do not edit manually.

/* AUTO-GENERATED REVIEW STUB
 * adapter_id: RRCReconfigurationComplete__logMeasAvailable__optional_presence_toggle
 * domain_id: RRCReconfigurationComplete__logMeasAvailable
 * message: RRCReconfigurationComplete
 * field: logMeasAvailable
 * operator_family: optional_presence_toggle
 * candidate_chain: criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->logMeasAvailable_r16
 * compile_validation: compile_verified
 * helper_function: nr_ue_fuzz_hook_apply_logmeasavailable_optional_presence_toggle
 * adapter_function: nr_ue_fuzz_hook_apply_logmeasavailable_optional_presence_toggle_adapter
 * payload_type: NR_RRCReconfigurationComplete_t
 * review points:
 *   - confirm_oai_struct_member_path
 *   - confirm_optional_branch_and_release_extension
 */
static bool nr_ue_fuzz_hook_apply_logmeasavailable_optional_presence_toggle(NR_UE_RRC_INST_t *rrc,
                              NR_RRCReconfigurationComplete_t *payload,
                              const char *mode)
{
  if (!payload)
    return false;

  if (!mode || !*mode)
    mode = "force_present_true";

  if (!strcasecmp(mode, "force_present_true")) {
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete)
      return false; /* review: CHOICE branch should already be selected */
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->logMeasAvailable_r16)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->logMeasAvailable_r16 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->logMeasAvailable_r16));
    *payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->logMeasAvailable_r16 = NR_UE_MeasurementsAvailable_r16__logMeasAvailable_r16_true;
    LOG_W(NR_RRC, "[UE %ld][HOOK] force logMeasAvailable in RRCReconfigurationComplete\\n", rrc->ue_id);
    return true;
  }

  if (!strcasecmp(mode, "omit")) {
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->logMeasAvailable_r16)
      return false;
    free(payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->logMeasAvailable_r16);
    payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->logMeasAvailable_r16 = NULL;
    LOG_W(NR_RRC, "[UE %ld][HOOK] omit logMeasAvailable in RRCReconfigurationComplete\\n", rrc->ue_id);
    return true;
  }

  return false;
}

static bool nr_ue_fuzz_hook_apply_logmeasavailable_optional_presence_toggle_adapter(NR_UE_RRC_INST_t *rrc, void *payload, const char *mode)
{
  return nr_ue_fuzz_hook_apply_logmeasavailable_optional_presence_toggle(rrc, (NR_RRCReconfigurationComplete_t *)payload, mode);
}

/* registry entry
{
    .target_msg = NR_UE_HOOK_MSG_RRC_RECONFIGURATION_COMPLETE,
    .message_name = "RRCReconfigurationComplete",
    .field_name = "logMeasAvailable",
    .operator_name = "optional_presence_toggle",
    .apply = nr_ue_fuzz_hook_apply_logmeasavailable_optional_presence_toggle_adapter,
},
*/

/* AUTO-GENERATED REVIEW STUB
 * adapter_id: RRCReconfigurationComplete__sigLogMeasConfigAvailable__optional_boolean_assignment
 * domain_id: RRCReconfigurationComplete__sigLogMeasConfigAvailable
 * message: RRCReconfigurationComplete
 * field: sigLogMeasConfigAvailable
 * operator_family: optional_boolean_assignment
 * candidate_chain: criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17
 * compile_validation: compile_verified
 * helper_function: nr_ue_fuzz_hook_apply_siglogmeasconfigavailable_optional_boolean_assignment
 * adapter_function: nr_ue_fuzz_hook_apply_siglogmeasconfigavailable_optional_boolean_assignment_adapter
 * payload_type: NR_RRCReconfigurationComplete_t
 * review points:
 *   - confirm_oai_struct_member_path
 *   - confirm_optional_branch_and_release_extension
 */
static bool nr_ue_fuzz_hook_apply_siglogmeasconfigavailable_optional_boolean_assignment(NR_UE_RRC_INST_t *rrc,
                              NR_RRCReconfigurationComplete_t *payload,
                              const char *mode)
{
  if (!payload)
    return false;

  if (!mode || !*mode)
    mode = "force_true";

  if (!strcasecmp(mode, "force_true")) {
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete)
      return false; /* review: CHOICE branch should already be selected */
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17));
    *payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17 = 1;
    LOG_W(NR_RRC, "[UE %ld][HOOK] force sigLogMeasConfigAvailable=true in RRCReconfigurationComplete\\n", rrc->ue_id);
    return true;
  }

  if (!strcasecmp(mode, "force_false")) {
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete)
      return false; /* review: CHOICE branch should already be selected */
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1));
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17)
      payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17 = CALLOC(1, sizeof(*payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17));
    *payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17 = 0;
    LOG_W(NR_RRC, "[UE %ld][HOOK] force sigLogMeasConfigAvailable=false in RRCReconfigurationComplete\\n", rrc->ue_id);
    return true;
  }

  if (!strcasecmp(mode, "omit")) {
    if (!payload->criticalExtensions.choice.rrcReconfigurationComplete
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1
        || !payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17)
      return false;
    free(payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17);
    payload->criticalExtensions.choice.rrcReconfigurationComplete->nonCriticalExtension->nonCriticalExtension->nonCriticalExtension->ue_MeasurementsAvailable_r16->ext1->sigLogMeasConfigAvailable_r17 = NULL;
    LOG_W(NR_RRC, "[UE %ld][HOOK] omit sigLogMeasConfigAvailable in RRCReconfigurationComplete\\n", rrc->ue_id);
    return true;
  }

  return false;
}

static bool nr_ue_fuzz_hook_apply_siglogmeasconfigavailable_optional_boolean_assignment_adapter(NR_UE_RRC_INST_t *rrc, void *payload, const char *mode)
{
  return nr_ue_fuzz_hook_apply_siglogmeasconfigavailable_optional_boolean_assignment(rrc, (NR_RRCReconfigurationComplete_t *)payload, mode);
}

/* registry entry
{
    .target_msg = NR_UE_HOOK_MSG_RRC_RECONFIGURATION_COMPLETE,
    .message_name = "RRCReconfigurationComplete",
    .field_name = "sigLogMeasConfigAvailable",
    .operator_name = "optional_boolean_assignment",
    .apply = nr_ue_fuzz_hook_apply_siglogmeasconfigavailable_optional_boolean_assignment_adapter,
},
*/

static const nr_ue_fuzz_hook_field_adapter_t auto_generated_field_adapters[] = {
    {
        .target_msg = NR_UE_HOOK_MSG_RRC_RECONFIGURATION_COMPLETE,
        .message_name = "RRCReconfigurationComplete",
        .field_name = "logMeasAvailable",
        .operator_name = "optional_presence_toggle",
        .apply = nr_ue_fuzz_hook_apply_logmeasavailable_optional_presence_toggle_adapter,
    },
    {
        .target_msg = NR_UE_HOOK_MSG_RRC_RECONFIGURATION_COMPLETE,
        .message_name = "RRCReconfigurationComplete",
        .field_name = "sigLogMeasConfigAvailable",
        .operator_name = "optional_boolean_assignment",
        .apply = nr_ue_fuzz_hook_apply_siglogmeasconfigavailable_optional_boolean_assignment_adapter,
    },
};

static const nr_ue_fuzz_hook_field_adapter_t *nr_ue_fuzz_hook_find_auto_field_adapter(const nr_ue_fuzz_hook_state_t *hook)
{
  if (!hook || !hook->field_mutation.enabled)
    return NULL;

  size_t count = sizeof(auto_generated_field_adapters) / sizeof(auto_generated_field_adapters[0]);
  for (size_t i = 0; i < count; ++i) {
    const nr_ue_fuzz_hook_field_adapter_t *adapter = &auto_generated_field_adapters[i];
    if (adapter->target_msg != hook->target_msg) continue;
    if (!nr_ue_fuzz_hook_text_eq(hook->field_mutation.message, adapter->message_name)) continue;
    if (!nr_ue_fuzz_hook_text_eq(hook->field_mutation.field, adapter->field_name)) continue;
    if (!nr_ue_fuzz_hook_text_eq(hook->field_mutation.operator_name, adapter->operator_name)) continue;
    return adapter;
  }
  
  return NULL;
}
